#India Flag

import turtle
from tkinter import *

win = turtle.Screen()
f = turtle.Turtle()
f.penup() # show cursor
f.goto(-180,60)
f.pendown()
f.begin_fill()
f.fillcolor("orange")
f.left(90)
f.forward(90)
f.right(90)
f.forward(400)
f.right(90)
f.forward(90)
f.right(90)
f.forward(400)
f.end_fill()
f.left(90)
f.forward(90)
f.left(90)
f.forward(400)
f.left(90)
f.forward(90)
f.left(90)
f.forward(400)
f.left(90)
f.forward(90)
f.begin_fill()
f.fillcolor("green")
f.forward(90)
f.left(90)
f.forward(400)
f.left(90)
f.forward(90)
f.left(90)
f.forward(400)
f.end_fill()
f.penup()
f.goto(25,59)
f.pendown()
f.begin_fill()
f.fillcolor("blue")
f.circle(45)
f.end_fill()
window = Tk()
lb1 = Label(window,text = "Vande Matram")
lb1.place(x=15,y=50)
fg = 'red',
font = 'Yuesei Magic'
window.title('Indian Flag done by Gaurav')
window.geometry("300x200")
window.mainloop()

f.penup()
f.goto(40,150)
f.write("Vande Matram", align="center", font = ("Yusei Magic",30))
f.pendown()
